# Site configuration
title: Kousha Ghodsizad
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kousha Ghodsizad
email: kousha@iraven.io
website: kousha.dev
phone: +31 6 47 15 49 99

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: koushamad
linkedin_username: kousha-ghodsizad
youtube_username: "@Coffee-Go"

# Additional icon links
additional_links:
  - title: kousha.dev
    icon: fas fa-globe
    url: https://kousha.dev

# About Section
about_profile_image: images/1629721583450.jpg
about_content: |
  I'm a passionate problem-solver dedicated to turning challenges into opportunities. My career has been defined by a commitment to excellence and collaboration. Whether I'm designing scalable CI/CD systems at Adyen, modernizing legacy architectures into microservices, or leading teams through complex technical transformations, I'm always focused on creating sustainable solutions that drive both individual and team success.

  I thrive in environments that encourage innovation and resilience, where obstacles are seen as a chance to think creatively and push boundaries. I place a high value on teamwork and enjoy mentoring others, fostering a positive and inclusive atmosphere where everyone's ideas are heard and valued. I'm always looking for ways to grow and support my colleagues in their own professional journeys.

  Outside of work, I enjoy activities like chess, which enhances my problem-solving skills, and rock climbing and hiking, which mirror my professional mindset: embracing calculated risks, adapting to change, and working toward a clear goal. Above all, I'm a curious and approachable collaborator who believes that the most rewarding challenges lead to the most impactful solutions.
  
  SKILLS
    Soft Skills: Collaboration & Teamwork, Leadership & Mentorship, Adaptability, Growth-Oriented Mindset
    Programming Languages: Golang, Python, PHP, SQL, NoSQL, Bash/Shell
    Cloud & Infrastructure: Kubernetes, Terraform, AWS, Private Cloud (OpenStack), HashiCorp Vault/Consul
    CI/CD & DevOps: ArgoCD, Argo Workflows, Argo Events, GitLab CI/CD, Jenkins, GitHub Actions
  
  +10 years of experience in software development.
  +4 years of experience in Management.
  +3 years of experience in DevOps.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Adyen
        link: https://Adyen.com/
        link_text: Adyen.com
        sub_title: Infrastructure Engineer (CICD)
        caption: Amsterdam - Jul 2023- Present
        quote: >
          As an Infrastructure Developer at Adyen since July 2023, I have been instrumental in designing and developing advanced Continuous Integration and Continuous Deployment (CI/CD) solutions, leveraging a diverse set of technologies to enhance operational efficiency and system reliability.
        description: |
          • AdyenCLI Development: Engineered AdyenCLI, a Golang-based command-line interface (CLI) application serving as a platform for executing plugins developed in Java, Go, Bash, and Python. Utilizing gRPC, I ensured secure and permission-based interactions with these plugins, facilitating seamless execution on user laptops.

          • High Availability Deployment: Deployed AdyenCLI across four distinct Kubernetes clusters in different regions, managing DNS with HashiCorp Consul to direct requests to the nearest healthy service. This setup, combined with JFrog for federated plugin serving, achieved 99.999% availability globally.

          • Workflow Automation with Argo: Designed and implemented highly available workflows using Kubernetes and Argo Workflows. By integrating Kubernetes' leader election mechanism with Argo CD and Argo Events, I established a system that ensures continuous workflow execution across multiple clusters, maintaining 99.999% availability.

          Tech stack:
          • Programming Languages: Proficient in Golang, Python, Shell, and PHP
          • Infrastructure and Cloud Technologies: OpenStack, Terraform
          • Containerization and Orchestration: Kubernetes
          • Secret Management: HashiCorp Vault
          • CI/CD Tools: GitLab, JFrog
          • Workflow Automation: Argo Workflows, Argo Events, Argo CD

      - layout: left
        title: Studocu
        link: https://studocu.com/
        link_text: studocu.com
        sub_title: Senior Software Engineer
        caption: Amsterdam - Jul 2022- Jul 2023
        quote: >
          As a Senior Software Engineer at StuDocu, I led critical projects to enhance system performance and observability.
        description: |
          • Enhanced Website Performance
          • Integrated Monitoring Tools
          • Optimized System Efficiency
          • Developed CI/CD Pipelines
          • Conducted Performance Workshops

          Technical Skills: Object-Oriented Programming (OOP), Agile Methodologies, Test-Driven Development
          Technologies: Laravel, AWS, MySQL, Redis, Go, PHP, Elasticsearch, Terraform

  - title: Education
    layout: list
    content:
      - layout: left
        title: Islamic Azad University
        caption: 2011 - 2015
        sub_title: BSc Computer Software Engineering
        quote: >
          Designing Innovative GIS & GPS-based Android Apps
        description: |
          Research study examining the development process for innovative GIS & GPS-based Android apps and their impact on user satisfaction.

      - layout: left
        title: Islamic Azad University
        caption: 2008 - 2011
        sub_title: ASc Computer Programming
        quote: >
          Enhancing Search and Rescue Robot Performance
        description: |
          Research study on developing and implementing novel algorithms for search and rescue robots.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in software engineering and DevOps some of my other interests and hobbies are:
      - Professional Chess Player
      - Rock Climbing
      - Running
      - Hiking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag